<template>
  <section class="section">
    <div class="container">
      <div class="columns intro">
        <div class="column is-6">
          <span
            style="
              font-family: poppins-semibold, poppins, sans-serif;
              font-size: 55px;
              font-weight: bold;
            "
            >Seal the deal in 60 seconds!</span
          >
          <p>The game that makes pitching fun and exciting.</p>
          <br /><br /><br /><br /><br /><br />

          <p>Powered by NTUitive</p>

          <br /><br /><br />

          <b-button type="is-primary" size="is-large">Start The Game</b-button>
        </div>
        <div class="column is-6">
          <img src="../assets/img.webp" style="border-radius: 50%" />
        </div>
      </div>

      <div class="container">
        <p
          class="font_8"
          style="line-height: 1.5em; text-align: center; font-size: 29px"
        >
          <span style="font-size: 29px"
            ><span style="letter-spacing: 0.05em"
              >A pitching game platform inspired by Silicon Valley Startup
              Pitching Card Game.</span
            ></span
          >
        </p>
      </div>

      <!-- <div class="container">
        <hero-bar :has-right-visible="false">
          PARTICIPATE EARLY. PLAY MORE, EARN MORE!
        </hero-bar>
      </div> -->

      <div class="container">
        <h2 class="font_2" style="text-align: center; font-size: 40px">
          <span class="color_15">How to Play</span>
        </h2>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>1.</hero-bar></div>
        <div class="column is-11">
          <p>
            In a team of 3 to 4 players, each team to determine their company’s
            name + industry + target user based on the cards generated by the
            online game system.
          </p>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>2.</hero-bar></div>
        <div class="column is-11">
          <p>
            Teams head to their Zoom breakrooms for 15-mins to discuss and
            design the most scalable and variable business model based on the
            chosen cards and prepare their 60-seconds pitch built on the
            following:
          </p>
          <li>Value Proposition (What will you offer?)</li>
          <li>Customers (Who will pay for your offer? Who will use it?)</li>
          <li>Processes (How will you produce and deliver?)</li>
          <li>Monetization (How will you generate revenue?)</li>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>3.</hero-bar></div>
        <div class="column is-11">
          <p>
            15-minutes later… Teams gather in the Zoom main room and gets
            creative and pitch their crazy startup idea. After all teams have
            pitched, the online game system generates a "hot trend" Card with a
            curveball question.
          </p>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>4.</hero-bar></div>
        <div class="column is-11">
          <p>
            Teams head back to individual breakout rooms for 1-min to discuss
            how they want to re-align their business model according to the “Hot
            Trend” card drawn.
          </p>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>5.</hero-bar></div>
        <div class="column is-11">
          <p>
            1 minute later… Teams meet back in main room and take turns to
            present their new business model in 60-seconds.
          </p>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>6.</hero-bar></div>
        <div class="column is-11">
          <p>
            At the end of each pitch, the other Teams will be given the option
            to challenge the pitching Team’s business idea.
          </p>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>7.</hero-bar></div>
        <div class="column is-11">
          <p>
            After all teams have addressed the challenge(s) posted by other
            teams, every individual player gets a chance to vote for the team
            with the best business model and funding potential based on the
            following criteria:
          </p>
          <li>Well-described business model</li>
          <li>Ability to pivot to cater to customer needs/market trends</li>
          <li>Potential to succeed</li>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>8.</hero-bar></div>
        <div class="column is-11">
          <p>
            Players can only vote for other teams. They will not be able to vote
            for their own team.
          </p>
        </div>
      </div>
      <div class="columns howtoplay">
        <div class="column is-1"><hero-bar>9.</hero-bar></div>
        <div class="column is-11">
          <p>The Team with the highest vote wins the game.</p>
        </div>
      </div>
      <img src="../assets/bg2.png" />
    </div>
  </section>
</template>

<style lang="scss">
.window {
  &__header {
    &__container {
      background: linear-gradient(90deg, #dbdbe4, #b284ed);
      padding: 10px;
      border-top-left-radius: 5px;
      border-top-right-radius: 5px;
      color: #ffffff;
      font-weight: 600;
      z-index: 1;
    }
  }
}
img {
  width: 100%;
  height: 100%;
}
.howtoplay {
  --bg-overlay-color: transparent;
  border-width: 6px 6px 6px 6px;
  border-style: solid solid solid solid;
  border-color: rgba(255, 145, 48, 1) rgba(255, 145, 48, 1)
    rgba(255, 145, 48, 1) rgba(255, 145, 48, 1);
  border-radius: 10px 10px 10px 10px;
  box-shadow: 0 7px 12px 12px rgba(254, 97, 97, 0.73);
  overflow: hidden;
  transform: translateZ(0);
  margin: -6px;
}
.intro {
  background-image: url(../assets/bg1.png);
}
.nan {
  height: 50px;
  background-image: url(../assets/bg3.png);
  margin: 30px 0;
}
</style>

<script>
export default {
  name: 'HomePage',

  components: {},
  data() {
    return {}
  },
  mounted() {},
  created() {},
  methods: {},
}
</script>
